# Generated by Django 5.1.2 on 2025-04-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_customuser_company_address_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
