# Generated by Django 5.1.2 on 2025-03-15 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewresponse",
            name="answer",
            field=models.TextField(help_text="Réponse du candidat"),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="approved",
            field=models.BooleanField(
                default=False, help_text="Indique si la réponse est approuvée"
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="post",
            field=models.ForeignKey(
                help_text="Poste associé à l'entretien",
                on_delete=django.db.models.deletion.CASCADE,
                to="post.post",
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="question",
            field=models.TextField(help_text="Question posée au candidat"),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="score",
            field=models.FloatField(
                default=0.0, help_text="Score attribué à la réponse"
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Horodatage de la réponse"
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur ayant fourni la réponse",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date et heure de création"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification",
            field=models.TextField(help_text="Message de la notification"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="read",
            field=models.BooleanField(
                default=False, help_text="Indique si la notification a été lue"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur recevant la notification",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="pdf_file",
            field=models.FileField(help_text="Fichier PDF uploadé", upload_to="pdfs/"),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="title",
            field=models.CharField(help_text="Titre du document PDF", max_length=255),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date et heure d'upload"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="accepted",
            field=models.BooleanField(
                default=False, help_text="Indique si un candidat a été accepté"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(help_text="Description détaillée du poste"),
        ),
        migrations.AlterField(
            model_name="post",
            name="final_date",
            field=models.DateField(
                blank=True, help_text="Date limite de candidature", null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(help_text="Titre du poste", max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Date et heure de création"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur ayant créé le poste",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
