# Generated by Django 5.1.2 on 2025-04-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_interviewresponse_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="salaire",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Salaire proposé en DH",
                max_digits=10,
                null=True,
            ),
        ),
    ]
