# Generated by Django 5.1.2 on 2025-03-12 22:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_interviewresponse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="dateFin",
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="approved",
            field=models.BooleanField(
                default=False, help_text="Indicates if the response is approved"
            ),
        ),
        migrations.AddField(
            model_name="interviewresponse",
            name="score",
            field=models.FloatField(
                default=0.0, help_text="Score assigned to the response"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="accepted",
            field=models.BooleanField(
                default=False, help_text="Indicates if the candidate has been accepted"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="final_date",
            field=models.DateField(
                blank=True, help_text="Application deadline for the job post", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="uploaded_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time when the post was created",
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="answer",
            field=models.TextField(help_text="Candidate's response to the question"),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="post",
            field=models.ForeignKey(
                help_text="Job post associated with the interview",
                on_delete=django.db.models.deletion.CASCADE,
                to="post.post",
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="question",
            field=models.TextField(
                help_text="Interview question asked to the candidate"
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the response was recorded"
            ),
        ),
        migrations.AlterField(
            model_name="interviewresponse",
            name="user",
            field=models.ForeignKey(
                help_text="User who provided the response",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="pdf_file",
            field=models.FileField(help_text="Uploaded PDF file", upload_to="pdfs/"),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="title",
            field=models.CharField(
                help_text="Title of the PDF document", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time when the file was uploaded"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(help_text="Detailed description of the job post"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(help_text="Title of the job post", max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                help_text="User who created the job post",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification",
                    models.TextField(help_text="Message of the notification"),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the notification has been read",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the notification was created",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User receiving the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when the report was generated",
                    ),
                ),
                ("message", models.TextField(help_text="Content of the report")),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Job post associated with the report",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with the report",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
