# Generated by Django 5.1.2 on 2025-04-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_delete_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewresponse",
            name="approved",
        ),
    ]
