# Generated by Django 5.1.2 on 2025-04-05 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_remove_interviewresponse_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de la demande (automatique)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        help_text="Statut de la candidature",
                        max_length=20,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Poste auquel l'utilisateur postule",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur qui postule",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
