# Generated by Django 5.1.2 on 2025-04-05 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_postapplication_cv_postapplication_interview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Raison du signalement (ex. : salaire incorrect)"
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date du signalement"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Poste signalé",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur qui signale",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
