# Generated by Django 5.1.2 on 2025-04-06 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planifié"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                        ],
                        default="planned",
                        help_text="Statut de l’entretien",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date de début (automatique à la création)",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="Date de fin (24h après le début)"),
                ),
                (
                    "questions",
                    models.JSONField(
                        blank=True,
                        help_text="Questions posées (format JSON)",
                        null=True,
                    ),
                ),
                (
                    "responses",
                    models.JSONField(
                        blank=True,
                        help_text="Réponses du candidat (format JSON)",
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True, help_text="Score attribué à l’entretien", null=True
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Poste lié à l’entretien",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Candidat passant l’entretien",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
