# Generated by Django 5.1.2 on 2025-04-09 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_interview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="accepted",
        ),
        migrations.AddField(
            model_name="postapplication",
            name="step",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("cv_compared", "CV comparé"),
                    ("interview_saved", "Interview sauvegardé"),
                    ("questions_generated", "Questions générées"),
                    ("answers_submitted", "Réponses soumises"),
                    ("evaluated", "Évalué"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="postapplication",
            name="application_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="postapplication",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="post.pdfdocument",
            ),
        ),
        migrations.AlterField(
            model_name="postapplication",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="post.interview",
            ),
        ),
        migrations.AlterField(
            model_name="postapplication",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="post.post"
            ),
        ),
        migrations.AlterField(
            model_name="postapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("accepte", "Accepté"),
                    ("refuse", "Refusé"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="postapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
